# *******************************************************************************
# Copyright (c) 2025 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Apache License Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0
#
# SPDX-License-Identifier: Apache-2.0
# *******************************************************************************

load("@os_autosd//toolchain/aib:defs.bzl", "aib_build_builder", "aib_script")

aib_script(
    name = "aib_build_script",
)

aib_build_builder(
    name = "builder",
    aib_script = ":aib_build_script",
    arch = "x86_64",
    distro = "autosd10",
)

package(default_visibility = ["//visibility:public"])
