# *******************************************************************************
# Copyright (c) 2025 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Apache License Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0
#
# SPDX-License-Identifier: Apache-2.0
# *******************************************************************************
load("@os_autosd//toolchain/aib:defs.bzl", "aib_build_disk", "aib_build_image")

aib_build_image(
    name = "simple",
    aib_define_files = [
        "//common_files:vars.yml",
        "//common_files:vars-devel.yml",
    ],
    aib_manifest = ":image.aib.yml",
    aib_script = "//images:aib_build_script",
    arch = "x86_64",
    distro = "autosd10",
    target = "qemu",
)

aib_build_disk(
    name = "simple-qemu",
    aib_bootc_image = ":simple",
    aib_builder_image = "//images:builder",
    aib_script = "//images:aib_build_script",
    arch = "x86_64",
    distro = "autosd10",
    target = "qemu",
)

package(default_visibility = ["//visibility:public"])
